### ISSUE TITLE
Redoing a failed cancel

### ISSUE THREAD

**Issue by kristinebrown10** [jmettraux/ruote#97]
Hi John,

Is there a way to redo a failed `unschedule_re_dispatch` in `on_cancel`? Similar to how you can `re_dispatch` a failed job for `on_workitem`? 

Thanks!
Kristine

**Comment by jmettraux** [comment]
Hello,

I'm sorry I have no idea. I haven't touched at Ruote in a long while. I'm now focusing on https://github.com/floraison/flor

Best regards,

John
